### ISSUE TITLE
As an Application Admin, I want to upload a list of candidates to the database.

### ISSUE THREAD

**Issue by kaljarv** [OpenVAA/voting-advice-application#182]
The list can be a CSV file or optionally another format, such as Google Sheet or Excel.

The data on the list are the basic details of candidates (and nominations), which they cannot change themselves. These are:

1. `Candidate`
  - first name
  - last name
  - party membership as `id` of the party
  - email address: this is considered the unique identifier (UID) for the candidates in terms of this tool [^1]
    - if feasible, add a setting in the code that defines the name of the field that is considered the UID, so that in the future this may be changed to, e.g., a social security number
  - published: if `true` publish the `Candidate`, default `false`
2. `Nomination`
  - a `Candidate` may have zero or more of these
  - candidate UID
  - constituency id
  - election id
  - election symbol
  - party id
  - published: if `true` publish the `Nomination`, default `false`
  - the UID for a `Nomination` is the combination of `candidate UID`, `election id`, `constituency id` and `party id`

### Data format

Optimally, it should be possible to pass three kinds of data:

A. Just candidates without nominations
B. Just nominations
C. Both candidates and nominations so that one row contains first the candidate's data and then the data for one nomination

Thus, the supported workflows would be (see below for details):

1. First the admin uploads a list of candidates (data type A). Later she uploads a list of nominations (B) for those candidates, with possibly multiple nominations for some. Even later she updates the nominations (B) with `election symbol` and `published` statuses.
2. The admin uploads a combined list of candidates (C) with one nomination each. The admin may later update these.
3. The admin overwrites the candidate and nomination data (C) for the supplied candidates.

### How to handle data updates

Optimally, there are two options for the updates:

1. Only update `Nominations` (data type B):
  - data is matched by the UID of the `Nomination`
  - the non-UID fields are overwritten, i.e., `election symbol` and `published`
  - if there is no existing `Nomination` with the UID, a new one is created
2. Update `Candidates` and overwrite their `Nominations` (data type C):
  - data is matched by the UID of the `Candidate`
  - the non-UID fields are overwritten
  - all the `Nominations` for that `Candidate` are deleted
  - one new `Nomination` the `Candidate` is created from the data supplied

### Data validation

The tool should show an error if:
- any ids or UIDs are not found, such as that of a party

### Other remarks

The UI for the Application Admin tools does not need to be mobile-friendly.

[^1]: The `Candidate` objects will also receive an `id` in Strapi which will be used in other contexts to identify them.

**Comment by johannalaitila** [comment]
For example: https://market.strapi.io/plugins/strapi-plugin-import-export-entries

**Comment by kaljarv** [comment]
@joonatanaatos asked some things. I've updated the main description to reflect these.

### How is the Candidate's party membership defined in the csv? (id vs name of the party)

As the id.

### How is the Nomination's party list defined in the csv? (Perhaps a list of ids in JSON format?)

Party list actually refers to the concept of an election list and just means one party. Thus, just one id.

### Should the imported entries be automatically published or should they be left as draft? (ie. should the publishedAt field be automatically defined?)

See the updated desc.

### The [Import Export Entries](https://market.strapi.io/plugins/strapi-plugin-import-export-entries) strapi plugin makes importing CSVs possible right away but it doesn't seem to support any custom middleware. Therefore I don't think it is possible to customize the import logic and do custom input validation (eg. verify that there are no duplicates) using the plugin. I think the best way of implementing the custom functionality is to fork the plugin repo and modify it ourselves. It has an MIT license, so there shouldn't be an issue with the licensing. How does this sound? If we go for this solution, there would be one more repository to maintain.

I think it'd be nice to try how this works. While building it, it would be good to also prepare for the possibility to also provide similar import functions for parties, consitituencies and questions in the future.

### What is meant by "data input by candidates have to be retained" regarding the importing functionality?

This refers
