### ISSUE TITLE
As an Application Admin, I want to send a login email to all candidates.

### ISSUE THREAD

**Issue by kaljarv** [OpenVAA/voting-advice-application#183]
The email should contain an introduction and a personal link that allows the candidate to login to the app and set their password.

The link is connected to a specific `Candidate` or `User`.

The introductory message should be defined by the Application Admin when sending the message.

Because the message may be multilingual, the link needs to be at an understandable location. If the link uses a label different from the url, the label needs to be specifiable by the Application Admin.

The UI for the Application Admin tools does not need to be mobile-friendly.

**Comment by joonatan-aatos** [comment]
What is the difference between this and #184 ? One of our interpretations is that #184 is for implementing the invite link and this issue is for sending the email through some UI. Then sending the email would not be included in #184 .

**Comment by kaljarv** [comment]
> What is the difference between this and #184 ? One of our interpretations is that #184 is for implementing the invite link and this issue is for sending the email through some UI. Then sending the email would not be included in #184 .

That's right. The actual sending of the emails would be included in this ticket and signing up in #184, but ofc they are highly interrelated.
