### ISSUE TITLE
As a Candidate, I want to able to log out from the app.

### ISSUE THREAD

**Issue by kaljarv** [OpenVAA/voting-advice-application#190]
Explicit and secure logging out of the app should be possible.

A modal notification should be displayed if the candidate has not yet filled all of their data. The notification should, however, automatically time out (e.g. in 30 sec) so that the candidate does not remain logged in by accident.

**Comment by johannalaitila** [comment]
Potentially helpful links:

- https://stackoverflow.com/questions/70436304/logout-user-from-strapi-react-native?rq=2
