### ISSUE TITLE
As a Candidate, I want my answers to automatically saved.

### ISSUE THREAD

**Issue by kaljarv** [OpenVAA/voting-advice-application#212]
The data input by the candidate should be auto-saved so that it's not lost if they navigate away from the page or because of connectivity issues.

Some candidates may spend considerable time writing even a single answer, so it might be useful to periodically auto-save these even without the focus leaving the field.

- However, if there is a way to gracefully handle the case where the contents are deleted by accident that would be nice. The option to intentionally delete the input should still be possible, of course.

To prevent issues of accidental deletion, the contents of already filled fields should not be auto-selected on focus.

**Comment by joonatan-aatos** [comment]
Is local storage sufficient or should the state be saved on the server?

**Comment by kaljarv** [comment]
I think optimally the state should be saved on the server, when the user deliberately moves the focus out from a field.

However, when they are filling a single field, i.e. a long open answer to a question, its contents should not be saved on the server because it might be still half-written. It would be nice, however, if even these texts-in-progress were recoverable after an accidental navigation away from the page – but only in the case that there isn't a non-empty saved answer for that field already on the server.

**Comment by joonatanaatos** [comment]
This is blocked by #199
