### ISSUE TITLE
As a Candidate, I don't want to lose data I've input if I accidentally log out.

### ISSUE THREAD

**Issue by kaljarv** [OpenVAA/voting-advice-application#255]
Specific care must be taken that no data the candidate has input to the app is unintentionally lost when logging out.

**Comment by joonatanaatos** [comment]
What is the difference between this and #212 ?

**Comment by kaljarv** [comment]
Technically both situations (logging out and other connectivity thingies) can be handled similarly, so really no meaningful difference :D
