### ISSUE TITLE
Localizable generic question types answer options

### ISSUE THREAD

**Issue by kaljarv** [OpenVAA/voting-advice-application#299]
Figure out a way to localize the answer options to enumerated types, including Likert questions.

For example, the basic Likert question types' answer options are defined in the `json` fields like this:

```
{
  "type": "Likert",
  "values": [
    {
      "key": 1,
      "label": "Disagree strongly"
    },
    {
      "key": 2,
      "label": "Disagree"
    },
    {
      "key": 3,
      "label": "Agree"
    },
    {
      "key": 4,
      "label": "Agree strongly"
    }
  ]
}
```

However, these values should be localizable. If we knew beforehand what the question types would be, we could just add these to `App Labels`, but the same kind of format should be used for all multiple choice or enumeration questions, which have to be generic and fully localizable.

How to do this? One option would be to create another content type `Enumerated Option` or something. These could be linked to a `Question` as one-to-many relations. The `Enumerated Option` would contain:

- `key`: number or id
- `label`: localizable string

**Comment by Chogster** [comment]
I've been away form the project for quite some time now but wanted to pitch in here with an idea. 
Disclaimer: I'm not fully aware of how these are implemented as of writing this, so please correct me if my assumptions are wrong or the suggestion is unfeasible.

Would it be feasible if the `label` property is changed to `labels`, which can contain multiple language labels, and also a `fallbackLanguage` is also added to the object structure? 

Example:
`{
  "type": "Likert",
  "values": [
    {
      "key": 1,
      "labels": [
          {
              "key": "en",
              "value":"Disagree strongly"
          },
          {
              "key": "fi",
              "value": "Täysin eri mieltä"
          },
          {
              "key": "de",
              "value": "Stimme überhaupt nicht zu"
          }
      ],
      "fallbackLang": "en"
    },
    {
        "key": 2,
        "labels": [
            {
                "key": "en",
                "value":"Disagree"
            },
            {
                "key": "fi",
                "value": "Eri mieltä"
            },
            {
                "key": "de",
                "value": "Stimme nicht zu"
            }
        ],
        "fallbackLang": "en"
      }
]
}`

**Comment by kaljarv** [comment]
Thanks, Bartu, for pitching in!

I think that your suggestion would work otherwise, but making the texts editable by the (non-developer) application admins might be a bit problematic. Currently we've been trying to implement all of the UI texts as localizable text fields in Strapi, and this json bit was a bit of a hot-fix.

**Comment by kaljarv** [comment]
As it turns out, the format @Chogster suggested, is the one we'll most likely go with 😅. See #317
