### ISSUE TITLE
Option to set up the app and connect to an external database

### ISSUE THREAD

**Issue by johannalaitila** [OpenVAA/voting-advice-application#39]
We can host the whole application, including database in a single Docker image. However in production settings when users install the app we probably want the database and the rest of app separated, so if the app needs updating the users can just get new Docker image without overriding the database contents.

This might need some kind of installer script that can take the database settings and call Strapi builder with the right settings. Or other option is just that we provide source code & Dockerfile, the users build the app themselves there and just set the DB url in an .env file.

**Comment by kaljarv** [comment]
Other possibilities are to circumvent Strapi completely and use an external API for the data calls.
