### ISSUE TITLE
Add Strapi token to the frontend dynamically  

### ISSUE THREAD

**Issue by johannalaitila** [OpenVAA/voting-advice-application#46]
If needed, update the documentation. The `/documentation/docker-setup-guide.md` file has some references to this topic.

**Comment by kaljarv** [comment]
Optionally, we could just give the same read privileges to unauthenticated users as are now granted with the API key. This would be very easy to accomplish.

See #360

**Comment by johannalaitila** [comment]
Superseded by #360
