### ISSUE TITLE
refactor: settings

### ISSUE THREAD

**Issue by kaljarv** [OpenVAA/voting-advice-application#496]
Settings handling is a bit ad hoc and should be refactored:

### Optional and default settings

All of the settings in `settings.json` are currently required. These should be converted to optional and default values put in place when loading them. Also, consider changing the format from `json` to `ts`, so we could use shared typing for the config and effective settings, which are now duplicated in the json schema and `global.d.ts`.

### Local and fetched settings

Effective settings are now derived from the `page` store so that they can incorporate `App Settings` fetched from the backend. This leads to problems if used in SSR and Sveltekit will promptly throw [an error](https://kit.svelte.dev/docs/state-management#avoid-shared-state-on-the-server). For this reason, the local settings from the json file are directly used, whereas elsewhere the `settings` store is used.

It'd be best to always use the combined settings and if this is not possible explicitly divide the settings into static (or local) and dynamic settings so that these are not confused.

### See also

- #432
- #459

**Comment by kaljarv** [comment]
- Strictly separate static settings from dynamics ones
- Defaults need to be provided statically though: how to automatically generate a Strapi (or other DP) content type that contains all of the necessary settings?

**Comment by anolpe** [comment]
- Survey out of analytics
- Schema to analytics from settings.json are static
- settings.json to .ts

**Comment by kaljarv** [comment]
Let's try to move the config file to the `/shared` folder so that it's accessible to the backend as well.
