### ISSUE TITLE
chore: issue labeling and format

### ISSUE THREAD

**Issue by kaljarv** [OpenVAA/voting-advice-application#534]
Some questions:
- backend/frontend
- do we need personas
- check other repos

**Comment by norppaa** [comment]
Some good ideologies: 
[https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63)

**Comment by kaljarv** [comment]
- Kill Personas
- Convert tag to status
- Fix colors
- Move away from User Stories

**Comment by kaljarv** [comment]
Depends #558

**Comment by kaljarv** [comment]
One further thing I forgot was that please update the docs regarding labels at the same time: `docs/contributing/how-to-use-labels.md`.
