### ISSUE TITLE
chore: update Playwright tests

### ISSUE THREAD

**Issue by kaljarv** [OpenVAA/voting-advice-application#561]
- Fix the rest
- Get username and password from mock data generator (separate into some config or smth fie for easy export)

**Comment by kaljarv** [comment]
@anolpe, can you still fix the `register.spec.ts` and also look into whether we could replace the URL RegExps with just a strict string match using `baseUrl` in all instances, i.e., the same URL that we pass to `page.goto`.

**Comment by anolpe** [comment]
@kaljarv I'm still working on `register.spec.ts` because it is not as simple as those other two tests and I've had to fix more things in it. I'll look into replacing those RegExps!
