### ISSUE TITLE
Create Navigation Bar component to be used throughout the application

### ISSUE THREAD

**Issue by jaguarfi** [OpenVAA/voting-advice-application#60]
The Navigation Bar component is a component that can be reused throughout the application.

<img width="370" alt="image" src="https://github.com/OpenVAA/voting-advice-application/assets/7520743/213b0810-e52c-40ed-8b48-a586624b2b0a">

See [Figma Designs](https://www.figma.com/file/uY9RTeNGmkSXjBYEWMmgGn/Election-Compass?node-id=297%3A5805&t=ZM8SK3lSAyXPV506-0)

**Comment by kaljarv** [comment]
Closed by #258
